name: Run Typescript
on:
  - pull_request
jobs:
  test:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
      - name: 📦 Install dependencies
        run: yarn
      - name: 🔨 Run Typescript
        run: yarn --cwd . ts:check
